<a href="https://colab.research.google.com/github/keenbm/Bike-Rent-Prediction/blob/master/Assignment/Python%20Basic%20Assignment/Python_Programming_Basic_Assignment_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



``` 
Python Programming Basic Assignment 8
Name : Bhavikkumar Modi
E-mail : bmodi700@gmail.com
```




1. Write a Python Program to Add Two Matrices?

In [49]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[4,8],[7,6]])
a+b

array([[ 5, 10],
       [10, 10]])

2. Write a Python Program to Multiply Two Matrices?


In [50]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[4,8],[7,6]])
a*b

array([[ 4, 16],
       [21, 24]])

3. Write a Python Program to Transpose a Matrix?


In [51]:
import numpy as np
a=np.array([[1,2],[3,4]])
a.transpose()

array([[1, 3],
       [2, 4]])

4. Write a Python Program to Sort Words in Alphabetic Order?

In [55]:
a=["Arm","Apple","Cat","Ball"]
a.sort()
a

['Apple', 'Arm', 'Ball', 'Cat']

5. Write a Python Program to Remove Punctuation From a String?

In [61]:
punctuation = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
word="Bhavik ,Modi "" \' "
for i in punctuation:
  word=word.replace(i,"")

word

'Bhavik Modi   '